
#### Namespace sanity ####

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources: [ "pods", "namespaces", "services" ]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: [ "deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: [ "configmaps" ]
    verbs: ["get", "list", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: dev
subjects:
  - kind: User
    name: eks-for-developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---

#### Namespace sanity ####

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: sanity
rules:
  - apiGroups: [""]
    resources: [ "pods", "namespaces", "services" ]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: [ "deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: [ "configmaps" ]
    verbs: ["get", "list", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: sanity
subjects:
  - kind: User
    name: eks-for-developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

---

#### Namespace sanity-demo ####

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: sanity-demo
rules:
  - apiGroups: [""]
    resources: [ "pods", "namespaces", "services" ]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: [ "deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: [ "configmaps" ]
    verbs: ["get", "list", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: sanity-demo
subjects:
  - kind: User
    name: eks-for-developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io