apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-for-ingress
  namespace: lab-nura
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-for-ingress
  template:
    metadata:
      name: nginx-for-ingress
      labels:
        name: nginx-for-ingress
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-for-ingress
  namespace: lab-nura
spec:
  selector:
    name: nginx-for-ingress
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
  namespace: lab-nura
spec:
  rules:
    - host: nginx.nurawiguna.local
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-nginx-for-ingress
              servicePort: 80
