apiVersion: v1
kind: Pod
metadata:
  name: nodejs-writer
  labels:
    name: nodejs-writer
  namespace: lab-nura 
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nodejs-writer
      image: nurawiguna/nodejs-writer
      volumeMounts:
        - mountPath: /app/html
          name: html