apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nura
  name: nura
  namespace: nura-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nura
  template:
    metadata:
      labels:
        app: nura
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 300Mi
            cpu: 300m
          limits:
            memory: 500Mi
            cpu: 500m