apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nodejs-env
data:
  APPLICATION: My Test Application

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-nodejs-env
stringData:
  VERSION: 1.0.0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nodejs-env
  name: nodejs-env
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-env
  strategy: {}
  template:
    metadata:
      labels:
        name: nodejs-env
    spec:
      containers:
      - image: nurawiguna/nodejs-env:1.0
        name: nodejs-env
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: config-nodejs-env
          - secretRef:
              name:  secret-nodejs-env
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nodejs-env
spec:
  type: NodePort
  selector:
    name: nodejs-env
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
