apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-web.fullname" . }}
  labels:
    {{- include "nodejs-web.labels" . | nindent 4 }}
  namespace: {{ .Values.image.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodejs-web.selectorLabels" . | nindent 4 }}
